# foundation/mappings/snowflake_mappings.py

class SnowflakeColumnMappings:
    """
    Contains column mappings for different Snowflake tables.
    Each dictionary maps source CSV column names to Snowflake column names.
    """
    
    PROPERTY_DIRECTORY = {
        'Management Fee Percent': 'MANAGEMENT_FEE_PERCENT',
        'Renewal Flat Fee': 'RENEWAL_FLAT_FEE',
        'Class': 'CLASS',
        'Maintenance Group': 'MAINTENANCE_GROUP',
        'Minimum Fee': 'MINIMUM_FEE',
        'Property Created By': 'PROPERTY_CREATED_BY',
        'Late Fee Daily Amount': 'LATE_FEE_DAILY_AMOUNT',
        'Management End Date': 'MANAGEMENT_END_DATE',
        'Property Type': 'PROPERTY_TYPE',
        'Lease Flat Fee': 'LEASE_FLAT_FEE',
        'Maintenance Notes': 'MAINTENANCE_NOTES',
        'Owner(s) - Phone Numbers': 'OWNERS__PHONE_NUMBERS',
        'Property Address': 'PROPERTY_ADDRESS',
        'Late Fee Type': 'LATE_FEE_TYPE',
        'Sqft': 'SQFT',
        'Grace Period': 'GRACE_PERIOD',
        'Portfolio': 'PORTFOLIO',
        'Owner(s)': 'OWNERS',
        'Listing Type': 'LISTING_TYPE',
        'Late Fee Base Amount': 'LATE_FEE_BASE_AMOUNT',
        'Management End Reason': 'MANAGEMENT_END_REASON',
        'Property City': 'PROPERTY_CITY',
        'Property': 'PROPERTY',
        'Property County': 'PROPERTY_COUNTY',
        'Description': 'DESCRIPTION',
        'Management Start Date': 'MANAGEMENT_START_DATE',
        'Grace Period Fixed Day': 'GRACE_PERIOD_FIXED_DAY',
        'Management Flat Fee': 'MANAGEMENT_FLAT_FEE',
        'Property Created On': 'PROPERTY_CREATED_ON',
        'Units': 'UNITS',
        'Property Name': 'PROPERTY_NAME',
        'Waive Fees When Vacant': 'WAIVE_FEES_WHEN_VACANT',
        'Property State': 'PROPERTY_STATE',
        'Property Street Address 1': 'PROPERTY_STREET_ADDRESS_1',
        'Vendor 1099 Payer': 'VENDOR_1099_PAYER',
        'Lease Fee Percent': 'LEASE_FEE_PERCENT',
        'Market Rent': 'MARKET_RENT',
        'Online Maintenance Request Instructions': 'ONLINE_MAINTENANCE_REQUEST_INSTRUCTIONS',
        'Renewal Fee Type': 'RENEWAL_FEE_TYPE',
        'Renewal Fee Percent': 'RENEWAL_FEE_PERCENT',
        'Management Fee Type': 'MANAGEMENT_FEE_TYPE',
        'MCC Enabled': 'MCC_ENABLED',
        'Property Zip': 'PROPERTY_ZIP',
        'Maintenance Limit': 'MAINTENANCE_LIMIT',
        'Grace Balance': 'GRACE_BALANCE',
        'Lease Fee Type': 'LEASE_FEE_TYPE'
    }

    RENT_ROLL = {
        'Property': 'PROPERTY',
        'Unit': 'UNIT',
        'Rent': 'RENT',
        'Past Due': 'PAST_DUE',
        'Late Count': 'LATE_COUNT'
    }

    APPLICANT = {
        'Name': 'NAME',
        'Email Address': 'EMAIL_ADDRESS',
        'Phone Number': 'PHONE_NUMBER',
        'Inquiry Received': 'INQUIRY_RECEIVED',
        'Last Activity Date': 'LAST_ACTIVITY_DATE',
        'Last Activity Type': 'LAST_ACTIVITY_TYPE',
        'Status': 'STATUS',
        'Move In Preference': 'MOVE_IN_PREFERENCE',
        'Max Rent': 'MAX_RENT',
        'Bed Bath Preference': 'BED_BATH_PREFERENCE',
        'Pet Preference': 'PET_PREFERENCE',
        'Monthly Income': 'MONTHLY_INCOME',
        'Credit Score': 'CREDIT_SCORE',
        'Lead Type': 'LEAD_TYPE',
        'Latest Interest Date': 'LATEST_INTEREST_DATE',
        'Latest Interest Source': 'LATEST_INTEREST_SOURCE',
        'Source': 'SOURCE',
        'Property': 'PROPERTY',
        'Unit': 'UNIT',
        'Assigned User': 'ASSIGNED_USER',
        'Notes': 'NOTES',
        'Applicant(s)': 'APPLICANTS',
        'Inquiry Type': 'INQUIRY_TYPE',
        'Total Interests Received': 'TOTAL_INTERESTS_RECEIVED',
        'Interests Received In Range': 'INTERESTS_RECEIVED_IN_RANGE',
        'Inactive Reason': 'INACTIVE_REASON'
    }

    UNIT = {
        'Unit Name': 'UNIT_NAME',
        'Market Rent': 'MARKET_RENT',
        'Default Deposit': 'DEFAULT_DEPOSIT',
        'Sqft': 'SQFT',
        'Bedrooms': 'BEDROOMS',
        'Bathrooms': 'BATHROOMS',
        'Tags': 'TAGS',
        'Revenue': 'REVENUE',
        'Description': 'DESCRIPTION',
        'Property': 'PROPERTY',
        'Property Name': 'PROPERTY_NAME',
        'Unit Address': 'UNIT_ADDRESS',
        'Unit Street Address 1': 'UNIT_STREET_ADDRESS_1',
        'Unit Street Address 2': 'UNIT_STREET_ADDRESS_2',
        'Unit City': 'UNIT_CITY',
        'Unit State': 'UNIT_STATE',
        'Unit Zip': 'UNIT_ZIP',
        'Marketing Title': 'MARKETING_TITLE',
        'Marketing Description': 'MARKETING_DESCRIPTION',
        'Advertised Rent': 'ADVERTISED_RENT',
        'Posted To Website': 'POSTED_TO_WEBSITE',
        'Posted To Internet': 'POSTED_TO_INTERNET',
        'YouTube URL': 'YOUTUBE_URL',
        'Unit Type': 'UNIT_TYPE',
        'Created On': 'CREATED_ON',
        'Rent Status': 'RENT_STATUS',
        'Legal Rent': 'LEGAL_RENT',
        'Application Fee': 'APPLICATION_FEE',
        'Rent Ready': 'RENT_READY',
        'Computed Market Rent': 'COMPUTED_MARKET_RENT',
        'Ready For Showing On': 'READY_FOR_SHOWING_ON',
        'Rentable UID': 'RENTABLE_UID',
        'Amenities': 'AMENITIES',
        'Appliances': 'APPLIANCES',
        'Utilities': 'UTILITIES',
        'Billed As': 'BILLED_AS'
    }

    UNIT_VACANCIES = {
        'Property': 'PROPERTY',
        'Unit': 'UNIT',
        'Tags': 'TAGS',
        'Bed/Bath': 'BED_BATH',
        'Sqft': 'SQFT',
        'Unit Status': 'UNIT_STATUS',
        'Rent Ready': 'RENT_READY',
        'Days Vacant': 'DAYS_VACANT',
        'Last Rent': 'LAST_RENT',
        'Scheduled Rent': 'SCHEDULED_RENT',
        'New Rent': 'NEW_RENT',
        'Last Move In': 'LAST_MOVE_IN',
        'Last Move Out': 'LAST_MOVE_OUT',
        'Available On': 'AVAILABLE_ON',
        'Next Move In': 'NEXT_MOVE_IN',
        'Description': 'DESCRIPTION',
        'Advertised Rent': 'ADVERTISED_RENT',
        'Posted To Website': 'POSTED_TO_WEBSITE',
        'Posted To Internet': 'POSTED_TO_INTERNET',
        'Unit Type': 'UNIT_TYPE',
        'Amenities Price': 'AMENITIES_PRICE',
        'Computed Market Rent': 'COMPUTED_MARKET_RENT',
        'Ready For Showing On': 'READY_FOR_SHOWING_ON',
        'Unit Turn Target Date': 'UNIT_TURN_TARGET_DATE'
    }

    WORK_ORDER_LABOR = {
        'Work Order Number': 'WORK_ORDER_NUMBER',
        'Date': 'LABOR_DATE',
        'Maintenance Tech': 'MAINTENANCE_TECH',
        'Property': 'PROPERTY',
        'Unit': 'UNIT',
        'Start Time': 'START_TIME',
        'End Time': 'END_TIME',
        'Worked Hours': 'WORKED_HOURS',
        'Billable Hours': 'BILLABLE_HOURS',
        'Hours Difference': 'HOURS_DIFFERENCE',
        'Work Order Status': 'WORK_ORDER_STATUS',
        'Description': 'DESCRIPTION',
        'Last Edited By': 'LAST_EDITED_BY',
        'Last Bill Created At': 'LAST_BILL_CREATED_AT',
        'Work Order Issue': 'WORK_ORDER_ISSUE',
        'Unit Turn ID': 'UNIT_TURN_ID',
        'Timer Start': 'TIMER_START',
        'Timer Stop': 'TIMER_STOP',
        'GL Account': 'GL_ACCOUNT'
    }

    WORK_ORDERS = {
        'Property': 'PROPERTY',
        'Priority': 'PRIORITY',
        'Work Order Type': 'WORK_ORDER_TYPE',
        'Home Warranty Expiration': 'HOME_WARRANTY_EXPIRATION',
        'Work Order Number': 'WORK_ORDER_NUMBER',
        'Job Description': 'JOB_DESCRIPTION',
        'Instructions': 'INSTRUCTIONS',
        'Status': 'STATUS',
        'Vendor': 'VENDOR',
        'Unit': 'UNIT',
        'Primary Resident': 'PRIMARY_RESIDENT',
        'Created At': 'CREATED_AT',
        'Estimate Req On': 'ESTIMATE_REQ_ON',
        'Estimated On': 'ESTIMATED_ON',
        'Estimate Amount': 'ESTIMATE_AMOUNT',
        'Scheduled Start': 'SCHEDULED_START',
        'Scheduled End': 'SCHEDULED_END',
        'Work Done On': 'WORK_DONE_ON',
        'Completed On': 'COMPLETED_ON',
        'Amount': 'AMOUNT',
        'Invoice': 'INVOICE',
        'Unit Turn ID': 'UNIT_TURN_ID',
        'Recurring': 'RECURRING',
        'Work Order Issue': 'WORK_ORDER_ISSUE',
        'Property Name': 'PROPERTY_NAME',
        'Service Request Number': 'SERVICE_REQUEST_NUMBER',
        'Service Request Description': 'SERVICE_REQUEST_DESCRIPTION',
        'Primary Resident Email': 'PRIMARY_RESIDENT_EMAIL',
        'Primary Resident Phone Number': 'PRIMARY_RESIDENT_PHONE_NUMBER',
        'Created By': 'CREATED_BY',
        'Assigned User': 'ASSIGNED_USER',
        'Estimate Approval Status': 'ESTIMATE_APPROVAL_STATUS',
        'Estimate Approved On': 'ESTIMATE_APPROVED_ON',
        'Estimate Approval Last Requested On': 'ESTIMATE_APPROVAL_LAST_REQUESTED_ON',
        'Last Billed On': 'LAST_BILLED_ON',
        'Canceled On': 'CANCELED_ON',
        'Corporate Charge Amount': 'CORPORATE_CHARGE_AMOUNT',
        'Discount Amount': 'DISCOUNT_AMOUNT',
        'Markup Amount': 'MARKUP_AMOUNT',
        'Tenant Total Charge Amount': 'TENANT_TOTAL_CHARGE_AMOUNT',
        'Vendor Bill Amount': 'VENDOR_BILL_AMOUNT',
        'Vendor Charge Amount': 'VENDOR_CHARGE_AMOUNT',
        'Resident Requested': 'RESIDENT_REQUESTED',
        'Requesting Resident': 'REQUESTING_RESIDENT',
        'Maintenance Limit': 'MAINTENANCE_LIMIT',
        'Status Notes': 'STATUS_NOTES',
        'Next Followup Date': 'NEXT_FOLLOWUP_DATE',
        'Vendor Trade': 'VENDOR_TRADE',
        'Unit Turn Category': 'UNIT_TURN_CATEGORY',
        'Vendor Portal Invoices': 'VENDOR_PORTAL_INVOICES'
    }

    @classmethod
    def get_mapping(cls, table_name: str) -> dict:
        """Get mapping dictionary for a given table name"""
        table_name = table_name.upper()
        mapping_dict = getattr(cls, table_name, None)
        if mapping_dict is None:
            raise ValueError(f"No mapping found for table: {table_name}")
        return mapping_dict
